# Generated by Django 4.2.7 on 2023-11-19 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vehicle_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
