# Generated by Django 4.2.7 on 2023-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_route_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(default='14 Turan st.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.CharField(default='123123', max_length=24, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(default='beb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='+77776665544', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='uin',
            field=models.CharField(default='123456789012', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
