# Generated by Django 4.2.7 on 2023-11-25 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver_address_driver_driving_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('fuelAmount', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('driverPhoto', models.ImageField(upload_to='images/')),
                ('carPhoto', models.ImageField(upload_to='images/')),
                ('fuelLevelPhotoBefore', models.ImageField(upload_to='images/')),
                ('fuelLevelPhotoAfter', models.ImageField(upload_to='images/')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehicle')),
            ],
        ),
    ]
