# Generated by Django 4.2.7 on 2023-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_route_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('finished', 'finished'), ('delayed', 'delayed'), ('canceled', 'canceled')], default='pending', max_length=16),
        ),
    ]
