# Generated by Django 4.2.7 on 2023-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_route_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(default='start point', max_length=100),
            preserve_default=False,
        ),
    ]
