# Generated by Django 4.2.7 on 2023-11-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auction_auctionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreport',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
