# Generated by Django 4.2.7 on 2023-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_fuelreport_user_remove_route_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreport',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
