# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_fuelreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreport',
            name='carPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='driverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuelLevelPhotoAfter',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='fuelLevelPhotoBefore',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
