# Generated by Django 4.2.7 on 2023-11-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220907_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='report',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name_plural': 'vechile part'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product',
            new_name='report',
        ),
    ]
