# Generated by Django 4.2.7 on 2023-11-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_report_alter_report_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='VechilePart',
        ),
    ]
