# Generated by Django 4.2.7 on 2023-11-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_route_origin'),
        ('products', '0007_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehicle'),
        ),
    ]
